trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: our-variables

steps:
# Keep GitHub's 'main' branch in-sync
- powershell: |
    git remote add github $env:MAPPED_GITHUB_URL
    git push github 'refs/remotes/origin/main:refs/heads/main'
    git push github 'refs/tags/*:refs/tags/*'

  env:
    MAPPED_GITHUB_URL: $(GitHubRepoUrl)   # map secret variable into env variable before using it
