using FSMExtension.Data;
using FSMExtension.Models;
using FSMExtension.Models.Fsm;
using FSMExtension.Repositories;
using FSMExtension.Services;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;

namespace FSMExtension.Controllers
{
    [ApiController]
    [Route("api/v1")]
    public class ConnectionsController : ControllerBase
    {
        public ConnectionsController(
            IOnsightConnectService connectService,
            IFsmApiService fsmApiService,
            IDomainMappingRepository domainRepo,
            ILogger<ConnectionsController> logger)
        {
            OnsightConnectService = connectService;
            FsmApiService = fsmApiService;
            DomainRepository = domainRepo;
            FsmMetadataBuilder = new FsmMetadataBuilder();
            Logger = logger;
        }

        private IOnsightConnectService OnsightConnectService { get; }

        private IFsmApiService FsmApiService { get; }

        private IDomainMappingRepository DomainRepository { get; }

        private IMetadataBuilder FsmMetadataBuilder { get; }

        private ILogger<ConnectionsController> Logger { get; }

        /// <summary>
        /// Endpoint which generates an Onsight Connect call URI using the given from/to email addresses.
        /// This endpoint is reachable by both the mobile UI (who generates this endpoint directly
        /// from the FSM mobile configuration) and by the web UI (which generates this as part
        /// of the GetConnections call below).
        /// 
        /// Note that the caller's platform (PC/iOS/Android) will be automatically detected.
        /// 
        /// Security note: as there is not built-in support for authentication from the FSM mobile
        /// configuration, this endpoint is open. As callers must still authenticate within the
        /// Onsight Connect application before using any URLs generated by this method, the risk is limited.
        /// 
        /// The URI that is generated by this method can then be directly accessed by the caller
        /// to start the Onsight Connect call.
        /// </summary>
        /// <param name="from">Email address of the person initiaing the Onsight Connect call</param>
        /// <param name="to"></param>
        /// <param name="meta">A semi-colon separated list of key-value pairs (colon separated) of data
        /// which will be included as metadata in the Onsight Connect call.</param>
        /// <returns></returns>
        [HttpGet]
        [Route("fsm/connection")]
        public async Task<IActionResult> GetConnection(
            [FromQuery] string from,
            [FromQuery] string to,
            [FromQuery] string meta)
        {
            Logger.LogDebug($"GetConnection: from={from}, to={to}, meta={meta}");

            // Try finding the Onsight API Key corresponding to the 'from' email address
            var domainMapping = await DomainRepository.GetFromUserEmailAsync(from);
            Logger.LogDebug($"GetConnection get domain_mapping success = {domainMapping != null}");
            if (domainMapping == null)
                return NotFound();

            // Generate metadata structure based on CrmSource and 'meta' string
            var metadata = FsmMetadataBuilder.Build(WebUtility.UrlDecode(meta));

            // Fetch and return Onsight Connect URL using APIKey + 'from' + 'to' + metadata struct
            var platform = Utils.DetectPlatform(Request);
            Logger.LogInformation($"Detected platform {platform}.");
            var uri = await OnsightConnectService.GetUriAsync(platform, domainMapping.OnsightApiKey, from, to, metadata);

            if (string.IsNullOrEmpty(uri))
                return NotFound();

            return Ok(uri);
        }

        /// <summary>
        /// Gets a list of Connections defined within the given CRM source object.
        /// 
        /// This endpoint is invoked by the web UI only (not mobile) and uses an internal
        /// Bearer token for authentication.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
        [Route("fsm/connections")]
        public async Task<IActionResult> GetConnections(
            [FromQuery(Name = "h")] string cloudHost,
            [FromQuery(Name = "a")] string accountId,
            [FromQuery(Name = "c")] string companyId,
            [FromQuery(Name = "av")] string activityId,
            [FromQuery(Name = "u")] string userId,
            [FromQuery(Name = "from")] string fromEmail)
        {
            var companyIdentifier = new FsmUserId(cloudHost, accountId, companyId, userId);

            // Look up FSM company (and its associated FSM auth token) based on 'accountId' + 'companyId'
            var domainMapping = await DomainRepository.GetFromFsmAccountIdAsync(accountId);
            var company = domainMapping.FsmAccount.FindCompany(companyId);
            if (company == null)
                return NotFound();

            // Get activity details based on 'crmSourceId'
            var activity = await FsmApiService.GetActivityAsync(cloudHost, company, activityId);
            if (activity == null)
                return NotFound();

            var contacts = new List<Contact>();

            // Get remote expert, either designated by the Equipment or the Activity.Contact
            var equipment = await FsmApiService.GetEquipmentAsync(cloudHost, company, domainMapping, activity.EquipmentId);
            var remoteExpert = await GetRemoteExpertAsync(cloudHost, company, activity, equipment, fromEmail);
            if (remoteExpert != null)
                contacts.Add(remoteExpert);

            // Get responsible's details from activity.responsibles[]. This is the assigned field worker.
            var responsibles = await FsmApiService.GetPersonsAsync(cloudHost, company, activity.Responsibles);
            contacts.AddRange(responsibles.Select(r => new Contact
            {
                Name = $"{r.FirstName} {r.LastName}",
                Title = r.PositionName ?? r.JobTitle,
                Role = ContactRole.FieldTech,
                Connection = GetConnectionUrl(fromEmail, r.EmailAddress, equipment?.Code, activity.Code)
            }));

            foreach (var c in contacts)
            {
                Logger.LogDebug($"/connections generated URL '{c.Connection}'");
            }

            return Ok(contacts);
        }

        /// <summary>
        /// Fetches contact information about the Activity's remote expert. The expert is either:
        ///     a) designated using custom fields associated with the Activity's equipment, or
        ///     b) the Activity's Contact.
        /// </summary>
        /// <returns></returns>
        private async Task<Contact> GetRemoteExpertAsync(
            string cloudHost,
            CompanyInfo company,
            Dtos.FsmActivity activity,
            Dtos.FsmEquipment equipment,
            string fromEmail)
        {
            var expertName = string.Empty;
            var expertEmail = string.Empty;
            var expertTitle = string.Empty;

            // Use Equipment's designated expert, if available
            var equipmentContact = equipment?.RemoteExpert;
            if (equipmentContact != null)
            {
                expertName = equipmentContact.FirstName;
                expertEmail = equipmentContact.EmailAddress;
            }

            if (string.IsNullOrEmpty(expertEmail))
            {
                // Otherwise, fall back to using the Activity's Contact
                var activityContact = await FsmApiService.GetContactAsync(cloudHost, company, activity.Contact);
                expertEmail = activityContact.EmailAddress;

                // Bail out if we don't have an "expert" associated with the Activity
                if (string.IsNullOrEmpty(expertEmail))
                    return null;

                expertName = $"{activityContact.FirstName} {activityContact.LastName}";
                expertTitle = activityContact.PositionName;
            }

            return new Contact
            {
                Name = expertName,
                Title = expertTitle,
                Role = ContactRole.Expert,
                Connection = GetConnectionUrl(fromEmail, expertEmail, equipment?.Code, activity.Code)
            };
        }

        /// <summary>
        /// Helper which generates the /fsm/connection URL string.
        /// </summary>
        /// <param name="fromEmail"></param>
        /// <param name="toEmail"></param>
        /// <param name="equipmentCode"></param>
        /// <param name="activityCode"></param>
        /// <returns></returns>
        private string GetConnectionUrl(string fromEmail, string toEmail, string equipmentCode, string activityCode)
        {
            var meta = new StringBuilder();
            if (!string.IsNullOrEmpty(equipmentCode))
                meta.Append($"eqp:{equipmentCode};");
            if (!string.IsNullOrEmpty(activityCode))
                meta.Append($"act:{activityCode};");

            return Url.Action(
                nameof(GetConnection),
                "Connections",
                new
                {
                    from = fromEmail,
                    to = toEmail,
                    meta = meta.ToString()
                }
            );
        }
    }
}
